export const menuList = [
    {
        id:'1',
        name:'上位规划',
        iconClass:'icon icon-guihua',
        childrenList:[
            {
                id:'11',
                name:'总规',
                funcInvokeUrl:'zonggui',
            },
            {
                id:'12',
                name:'控规',
                funcInvokeUrl:'konggui',
            },
            {
                id:'13',
                name:'土规',
                funcInvokeUrl:'tugui',
            },
        ]
    },
    {
        id:'2',
        name:'数据管理',
        iconClass:'icon icon-shuju',
        childrenList:[
            {
                id:'21',
                name:'总规',
                funcInvokeUrl:'zonggui',
            },
            {
                id:'22',
                name:'控规',
                funcInvokeUrl:'konggui',
            },
            {
                id:'23',
                name:'土规',
                funcInvokeUrl:'tugui',
            },
        ]
    },
    {
        id:'3',
        name:'旧改现状',
        iconClass:'icon icon-xianzhuang',
        childrenList:[
            {
                id:'31',
                name:'总规',
                funcInvokeUrl:'zonggui',
            },
            {
                id:'32',
                name:'控规',
                funcInvokeUrl:'konggui',
            },
            {
                id:'33',
                name:'土规',
                funcInvokeUrl:'tugui',
            },
        ]
    },
    {
        id:'4',
        name:'项目进展',
        iconClass:'icon icon-xiangmu',
        childrenList:[
            {
                id:'41',
                name:'总规',
                funcInvokeUrl:'zonggui',
            },
            {
                id:'42',
                name:'控规',
                funcInvokeUrl:'konggui',
            },
            {
                id:'43',
                name:'土规',
                funcInvokeUrl:'tugui',
            },
        ]
    },
]