export const layerData = [
    {
        "children": [
            {
                "children": [],
                "layers": [
                    {
                        "id": "f1e02709-63e6-4b21-b2f1-8f1425f3e794",
                        "text": "长平村",
                        // "url": "http://81.71.142.155:6700/Models/Tianhe/Tianhe_qx_A/tileset.json",
                        "url": "https://112.74.166.19:6443/arcgis/rest/services/kexuecheng/hp_changping/MapServer",
                        "layerType": "120010",
                        "featureType": "",
                        "type": "{editable:0,queryable:1,queryCon:0,isBaseMap:0,isShow:1,extent:0,order:1261}",
                        "layerTable": "",
                        "isBaseMap": "0",
                        "paramId": "d0a70d6b-1199-485c-9795-bdb82c5fd85f",
                        "state": {
                            "extent": "0",
                            "queryable": "1",
                            "editable": "0",
                            "checked": true,
                            "isBaseMap": "0",
                            "queryCon": "0",
                            "isShow": "1"
                        },
                        "data": "{\"dataSource\":\"\",\"dataVersion\":\"\",\"coordinateSystem\":\"\",\"area\":\"\",\"projectionType\":\"\",\"updateCycle\":\"\",\"renderLayerId\":\"\",\"featureUrl\":\"\",\"isVisable\":\"\",\"viewPort\":\"\",\"senceExtendData\":\"[{\\\"key\\\":\\\"\\\",\\\"value\\\":\\\"\\\",\\\"explain\\\":\\\"\\\"}]\",\"regExAndValue\":\"{\\\"regObj\\\":{\\\"regEx_0\\\":\\\"\\\"},\\\"valueObj\\\":{\\\"value_0\\\":\\\"\\\"}}\",\"charset\":\"UTF-8\",\"isCacheText\":\"0\",\"isCacheImage\":\"0\",\"dataSourceId\":\"\",\"format\":\"\",\"userName\":\"\",\"password\":\"\",\"layerTypeCn\":\"3dtiles\",\"owner\":\"admin\",\"layerId\":\"\",\"createTime\":{\"date\":28,\"hours\":11,\"seconds\":19,\"month\":8,\"timezoneOffset\":-480,\"year\":120,\"minutes\":52,\"time\":1601265139165,\"day\":1},\"illustration\":\"\",\"layerName\":\"\",\"picture\":\"\"}",
                        "extent": null,
                        "nameCn": "长平村",
                        "order": 1261,
                        "uuid": null,
                        "isProxy": "http://81.71.142.155:6700/Models/Tianhe/Tianhe_qx_A/tileset.json",
                        "proxyUrl": "",
                        "visibleMinZoom": "",
                        "visibleMaxZoom": "",
                        "userId": "191ccbc3-b05d-4365-9da0-577197f2bba3",
                        "dirLayerId": "4a5fad77-f8c2-40db-8a1b-8f76c3542c09",
                        "mapParam": null,
                        "dataSourceId": "",
                        "pkColumn": "",
                        "geometryColumn": "",
                        "isVector": "",
                        "baseColor": "",
                        "specular": "",
                        "isSelfPoPup": "",
                        "selfPoPupContent": "",
                        "remarks": "",
                        "styleManagerId": "",
                        "layerVersion": "v1",
                        "layerAggregateName": "",
                        "proxyType": "0"
                    }
                ],
                "pid": "6be1ef04-0268-4bc6-a178-851fb93a8c4b",
                "id": "a4dc5bcd-4f44-49a6-af59-37f3b82b2d91",
                "text": "更新红线",
                "dirOrder": 6,
                "iconCls": "icon-folder",
                "info": "更新红线"
            },
            {
                "children": [],
                "layers": [
                    {
                        "id": "f1e02709-63e6-4b21-b2f1-8f1425f3e748",
                        "text": "黄埔区土地利用现状",
                        // "url": "http://81.71.142.155:6700/Models/Tianhe/Tianhe_qx_A/tileset.json",
                        "url": "https://112.74.166.19:6443/arcgis/rest/services/kexuecheng/hp_landState/MapServer",
                        "layerType": "120010",
                        "featureType": "",
                        "type": "{editable:0,queryable:1,queryCon:0,isBaseMap:0,isShow:1,extent:0,order:1261}",
                        "layerTable": "",
                        "isBaseMap": "0",
                        "paramId": "d0a70d6b-1199-485c-9795-bdb82c5fd85f",
                        "state": {
                            "extent": "0",
                            "queryable": "1",
                            "editable": "0",
                            "checked": false,
                            "isBaseMap": "0",
                            "queryCon": "0",
                            "isShow": "1"
                        },
                        "data": "{\"dataSource\":\"\",\"dataVersion\":\"\",\"coordinateSystem\":\"\",\"area\":\"\",\"projectionType\":\"\",\"updateCycle\":\"\",\"renderLayerId\":\"\",\"featureUrl\":\"\",\"isVisable\":\"\",\"viewPort\":\"\",\"senceExtendData\":\"[{\\\"key\\\":\\\"\\\",\\\"value\\\":\\\"\\\",\\\"explain\\\":\\\"\\\"}]\",\"regExAndValue\":\"{\\\"regObj\\\":{\\\"regEx_0\\\":\\\"\\\"},\\\"valueObj\\\":{\\\"value_0\\\":\\\"\\\"}}\",\"charset\":\"UTF-8\",\"isCacheText\":\"0\",\"isCacheImage\":\"0\",\"dataSourceId\":\"\",\"format\":\"\",\"userName\":\"\",\"password\":\"\",\"layerTypeCn\":\"3dtiles\",\"owner\":\"admin\",\"layerId\":\"\",\"createTime\":{\"date\":28,\"hours\":11,\"seconds\":19,\"month\":8,\"timezoneOffset\":-480,\"year\":120,\"minutes\":52,\"time\":1601265139165,\"day\":1},\"illustration\":\"\",\"layerName\":\"\",\"picture\":\"\"}",
                        "extent": null,
                        "nameCn": "黄埔区土地利用现状",
                        "order": 1261,
                        "uuid": null,
                        "isProxy": "http://81.71.142.155:6700/Models/Tianhe/Tianhe_qx_A/tileset.json",
                        "proxyUrl": "",
                        "visibleMinZoom": "",
                        "visibleMaxZoom": "",
                        "userId": "191ccbc3-b05d-4365-9da0-577197f2bba3",
                        "dirLayerId": "4a5fad77-f8c2-40db-8a1b-8f76c3542c09",
                        "mapParam": null,
                        "dataSourceId": "",
                        "pkColumn": "",
                        "geometryColumn": "",
                        "isVector": "",
                        "baseColor": "",
                        "specular": "",
                        "isSelfPoPup": "",
                        "selfPoPupContent": "",
                        "remarks": "",
                        "styleManagerId": "",
                        "layerVersion": "v1",
                        "layerAggregateName": "",
                        "proxyType": "0"
                    },
                    {
                        "id": "1c401e0d-695b-47ad-a3d2-27d7d2a2d4e3",
                        "text": "黄埔区控制性详细规划",
                        // "url": "http://81.71.142.155:6700/Models/Guangzhou/GZ_dalou/tilesetv4.json",
                        "url": "https://112.74.166.19:6443/arcgis/rest/services/kexuecheng/hp_konggui/MapServer",
                        "layerType": "120010",
                        "featureType": "",
                        "type": "{editable:0,queryable:1,queryCon:0,isBaseMap:0,isShow:1,extent:0,order:1372}",
                        "layerTable": "",
                        "isBaseMap": "0",
                        "paramId": "d0a70d6b-1199-485c-9795-bdb82c5fd85f",
                        "state": {
                            "extent": "0",
                            "queryable": "1",
                            "editable": "0",
                            "checked": true,
                            "isBaseMap": "0",
                            "queryCon": "0",
                            "isShow": "1"
                        },
                        "data": "{\"dataSource\":\"\",\"dataVersion\":\"\",\"coordinateSystem\":\"\",\"area\":\"\",\"projectionType\":\"\",\"updateCycle\":\"\",\"renderLayerId\":\"\",\"featureUrl\":\"\",\"isVisable\":\"\",\"viewPort\":\"\",\"senceExtendData\":\"[{\\\"key\\\":\\\"\\\",\\\"value\\\":\\\"\\\",\\\"explain\\\":\\\"\\\"}]\",\"regExAndValue\":\"{\\\"regObj\\\":{\\\"regEx_0\\\":\\\"\\\"},\\\"valueObj\\\":{\\\"value_0\\\":\\\"\\\"}}\",\"charset\":\"UTF-8\",\"isCacheText\":\"0\",\"isCacheImage\":\"0\",\"dataSourceId\":\"\",\"format\":\"\",\"userName\":\"\",\"password\":\"\",\"layerTypeCn\":\"3dtiles\",\"owner\":\"admin\",\"layerId\":\"\",\"createTime\":{\"date\":19,\"hours\":18,\"seconds\":10,\"month\":9,\"timezoneOffset\":-480,\"year\":120,\"minutes\":45,\"time\":1603104310706,\"day\":1},\"illustration\":\"\",\"layerName\":\"\",\"picture\":\"\"}",
                        "extent": null,
                        "nameCn": "黄花岗控制性详细规划",
                        "order": 1372,
                        "uuid": null,
                        "isProxy": "http://81.71.142.155:6700/Models/Guangzhou/GZ_dalou/tilesetv4.json",
                        "proxyUrl": "",
                        "visibleMinZoom": "",
                        "visibleMaxZoom": "",
                        "userId": "191ccbc3-b05d-4365-9da0-577197f2bba3",
                        "dirLayerId": "fa112141-945f-4d84-a4f6-8554164384c6",
                        "mapParam": null,
                        "dataSourceId": "",
                        "pkColumn": "",
                        "geometryColumn": "",
                        "isVector": "",
                        "baseColor": "",
                        "specular": "",
                        "isSelfPoPup": "",
                        "selfPoPupContent": "",
                        "remarks": "",
                        "styleManagerId": "",
                        "layerVersion": "v1",
                        "layerAggregateName": "",
                        "proxyType": "0"
                    }
                ],
                "pid": "6be1ef04-0268-4bc6-a178-851fb93a8c4b",
                "id": "a4dc5bcd-4f44-49a6-af59-37f3b82b2d92",
                "text": "上位规划",
                "dirOrder": 6,
                "iconCls": "icon-folder",
                "info": "上位规划"
            }
        ],
        "layers": [],
        "pid": "c91e843b-87f9-496f-876a-eae776a9ce2d",
        "id": "6be1ef04-0268-4bc6-a178-851fb93a8c4b",
        "text": "基础数据",
        "dirOrder": 1,
        "iconCls": "icon-folder",
        "info": ""
    }
]